---
      - name: Install dependencies
        yum:
          name:
            - wget
            - unzip
            - java-17-openjdk
          state: present
  
      - name: Download Sonarqube binary zip
        get_url:
          url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.7.96285.zip
          dest: /home/ec2-user/sonarqube-9.9.7.96285.zip
  

      - name: Unzip Sonarqube
        unarchive:
          src: /home/ec2-user/sonarqube-9.9.7.96285.zip
          dest: /home/ec2-user/
          remote_src: yes
  


      - name: Create sonarqube systemd service
        copy:
          dest: /etc/systemd/system/sonarqube.service
          content: |
            [Unit]
            Description=SonarQube service
            After=syslog.target network.target
  
            [Service]
            Type=forking
            User=ec2-user
            Group=ec2-user
            WorkingDirectory=/home/ec2-user/sonarqube-9.9.7.96285
            ExecStart=/bin/bash /home/ec2-user/sonarqube-9.9.7.96285/bin/linux-x86-64/sonar.sh start
            ExecStop=/bin/bash /home/ec2-user/sonarqube-9.9.7.96285/bin/linux-x86-64/sonar.sh stop
            Restart=always
            LimitNOFILE=65536
            LimitNPROC=4096
            
            [Install]
            WantedBy=multi-user.target

      - name: Reload systemd daemon
        systemd:
          daemon_reload: yes

      - name: Enable and start Sonarqube service
        systemd:
          name: sonarqube
          enabled: yes
          state: started
...


