---
# tasks file for kubernetes
      - name: unzip install
        yum:
          name: unzip
          state: present

      - name: Download AWS CLI installer
        get_url:
          url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
          dest: "/tmp/awscliv2.zip"

      - name: Unzip AWS CLI installer
        command: "unzip /tmp/awscliv2.zip -d /tmp/"

      - name: Install AWS CLI
        command: "sudo /tmp/aws/install"

      - name: Add Kubernetes repository
        copy:
          dest: "/etc/yum.repos.d/kubernetes.repo"
          content: |
            [kubernetes]
            name=Kubernetes
            baseurl=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
            enabled=1
            gpgcheck=1
            gpgkey=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
        become: yes

      - name: Install kubectl
        yum:
          name: kubectl
          state: present
        become: yes

      - name: Download latest kops binary
        shell: |
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
        args:
          chdir: /tmp

      - name: Make kops executable
        file:
          path: /tmp/kops
          mode: '0755'

      - name: Move kops binary to /usr/local/bin
        command: mv /tmp/kops /usr/local/bin/kops
        become: true

...









