---
# tasks file for jenkins
#install and run Jenkins server

      - name: wget install
        yum:
          name: wget
          state: present

      - name: git install
        yum:
          name: git
          state: present

      - name: JDK install
        yum:
          name: java-17-openjdk
          state: present
      
      - name: Enable jenkins repo
        shell:
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

          
      - name: Jenkins key download
        shell:
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      
      
      - name: Jenkins install
        yum:
          name: jenkins
          state: present
      
      - name: Daemon reload
        systemd: 
          daemon_reload: yes
  

      - name: Jenkins service starts
        systemd: 
          name: jenkins
          enabled: yes          
          state: started




...




