---
# tasks file for jenkins
#install and run Jenkins server

      - name: wget install
        yum:
          name: wget
          state: present

      - name: git install
        yum:
          name: git
          state: present

      - name: JDK install
        yum:
          name: java-17-openjdk
          state: present
      
      - name: Enable jenkins repo
        shell:
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

          
      - name: Jenkins key download
        shell:
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      
      
      - name: Jenkins install
        yum:
          name: jenkins
          state: present
      
      - name: Daemon reload
        systemd: 
          daemon_reload: yes
  

      - name: Jenkins service starts
        systemd: 
          name: jenkins
          enabled: yes          
          state: started



      - name: unzip install
        yum:
          name: unzip
          state: present

      - name: Check if AWS CLI installer zip exists
        stat:
          path: /tmp/awscliv2.zip
        register: aws_zip

      - name: Download AWS CLI installer
        get_url:
          url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
          dest: "/tmp/awscliv2.zip"
        when: not aws_zip.stat.exists

      - name: Unzip AWS CLI installer
        command: unzip -o /tmp/awscliv2.zip -d /tmp/
        when: not aws_zip.stat.exists

      - name: Install AWS CLI
        command: "sudo /tmp/aws/install"
        when: not aws_zip.stat.exists

      - name: Add Kubernetes repository
        copy:
          dest: "/etc/yum.repos.d/kubernetes.repo"
          content: |
            [kubernetes]
            name=Kubernetes
            baseurl=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
            enabled=1
            gpgcheck=1
            gpgkey=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
        become: yes

      - name: Install kubectl
        yum:
          name: kubectl
          state: present
        become: yes

      - name: Download latest kops binary
        shell: |
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
        args:
          chdir: /tmp

      - name: Make kops executable
        file:
          path: /tmp/kops
          mode: '0755'

      - name: Move kops binary to /usr/local/bin
        command: mv /tmp/kops /usr/local/bin/kops
        become: true


...




